# Generated by Django 4.2.1 on 2023-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andon',
            fields=[
                ('login', models.CharField(max_length=255)),
                ('ticket', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('andon_alerts', models.DateTimeField()),
                ('acknowledge', models.DateTimeField()),
                ('andon_resolved', models.DateTimeField()),
            ],
            options={
                'db_table': 'andon',
            },
        ),
    ]
