# Generated by Django 4.2.1 on 2023-05-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_andon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andon',
            old_name='acknowledge',
            new_name='andon_acknowledge',
        ),
    ]
