# Generated by Django 4.2.1 on 2023-05-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_rename_acknowledge_andon_andon_acknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='andon_acknowledge',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='andon',
            name='andon_alerts',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='andon',
            name='andon_resolved',
            field=models.DateTimeField(null=True),
        ),
    ]
