# Generated by Django 4.2.1 on 2023-05-31 16:33

import EmployeeApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_alter_andon_andon_acknowledge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='ticket',
            field=EmployeeApp.models.CustomCharField(primary_key=True, serialize=False),
        ),
    ]
