# Generated by Django 4.2.1 on 2023-05-31 16:52

import EmployeeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_alter_andon_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='ticket',
            field=models.IntegerField(primary_key=True),
        ),
    ]
