# Generated by Django 4.2.1 on 2023-06-04 02:46

import EmployeeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_alter_andon_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='ticket',
            field=models.BigIntegerField(primary_key=True),
        ),
    ]
