# Generated by Django 4.2.1 on 2023-06-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_alter_andon_ticket'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='andon',
        #     name='ticket',
        #     field=models.BigAutoField(primary_key=True, serialize=False),
        # ),
    ]
