# Generated by Django 4.2.1 on 2023-06-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_alter_andon_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='andon',
            name='machineId',
            field=models.CharField(default='default_value', max_length=255),
        ),
        # migrations.AlterField(
        #     model_name='andon',
        #     name='ticket',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
