# Generated by Django 4.2.1 on 2023-06-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0009_alter_andon_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='andon',
            name='total_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='andon',
            name='ticket',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
