# Generated by Django 4.2.1 on 2023-06-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0010_andon_total_time_alter_andon_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='total_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
