# Generated by Django 4.2.1 on 2023-06-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0011_alter_andon_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='login',
            field=models.CharField(default='XYZ', max_length=255),
        ),
        migrations.AlterField(
            model_name='andon',
            name='machineId',
            field=models.CharField(max_length=255),
        ),
    ]
