# Generated by Django 4.2.1 on 2023-06-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breakdownCategory',
            fields=[
                ('breakdownCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('breakdownCategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='machines',
            fields=[
                ('machineId', models.AutoField(primary_key=True, serialize=False)),
                ('machineName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
            ],
        ),
    ]
