# Generated by Django 4.2.1 on 2023-06-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andonApp', '0002_assemblyline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubBreakdownCategory',
            fields=[
                ('subBreakdownCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('subBreakdownCategoryName', models.CharField(max_length=100)),
                ('breakdownCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andonApp.breakdowncategory')),
            ],
        ),
    ]
