# Generated by Django 4.2.1 on 2023-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andonApp', '0003_subbreakdowncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFloor',
            fields=[
                ('shopfloorId', models.AutoField(primary_key=True, serialize=False)),
                ('shopfloorName', models.CharField(max_length=100)),
            ],
        ),
    ]
