# Generated by Django 4.2.1 on 2023-06-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andonApp', '0004_shopfloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAssemblyLine',
            fields=[
                ('subAssemblylineId', models.AutoField(primary_key=True, serialize=False)),
                ('subAssemblylineName', models.CharField(max_length=100)),
                ('assemblylineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andonApp.assemblyline')),
            ],
        ),
    ]
