# Generated by Django 4.2.1 on 2023-06-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andonApp', '0005_subassemblyline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReceipe',
            fields=[
                ('productReceipeId', models.AutoField(primary_key=True, serialize=False)),
                ('productId', models.CharField(max_length=100)),
                ('stages', models.PositiveIntegerField()),
                ('stage1', models.PositiveIntegerField()),
                ('target_time1', models.DurationField()),
                ('target_per_minute1', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('target_per_hour1', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('skill_matrix1', models.CharField(max_length=100)),
                ('stage2', models.PositiveIntegerField()),
                ('target_time2', models.DurationField()),
                ('target_per_minute2', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('target_per_hour2', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('skill_matrix2', models.CharField(max_length=100)),
            ],
        ),
    ]
