# Generated by Django 4.2.1 on 2023-05-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser_access',
        ),
    ]
